Dependencies:
 - 'on': ['Linux', 'FreeBSD', 'Windows', 'Android']
   'require':
    'frameworks/extra-cmake-modules': '@same'
    'third-party/zxing-cpp': '@latest'

Options:
 test-before-installing: True
 require-passing-tests-on: ['Linux', 'FreeBSD', 'Windows']
